name = "car-km-trackers"
main = "src/index.js"
compatibility_date = "2026-09-23"

[[d1_databases]]
binding = "DB"
database_name = "car-km-tracker"
database_id = "2ef3e763-4ff4-440f-8d05-82252882233d"
migrations_dir = "migrations"
